### ISSUE TITLE
Inter-page, Intra-book cooked links broken

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-publishing#132]
Context is missing on generated intra-book links, for example, the links in the glossary index in Introductory Statistics on CTE Dev.

Example link in the Index: (at http://cte-cnx-dev.cnx.org/contents/MBiUQmmY@17.55:r9gqD6J7@1/Index)

term: binomial distribution
link text: 8.3 | A Population Proportion
link href: http://cte-cnx-dev.cnx.org/contents/40dc2960-9ad3-4f5a-acd4-606a1f6fbfb1@7#term160

link should be: http://cte-cnx-dev.cnx.org/contents/30189442-6998-4686-ac05-ed152b91b9de@17.55:40dc2960-9ad3-4f5a-acd4-606a1f6fbfb1@7#term160

**Comment by karenc** [comment]
Webview has been converting intra-book links, so I've done a fix in webview: https://github.com/Connexions/webview/pull/1426

So now when you go to http://cte-cnx-dev.cnx.org/contents/MBiUQmmY@17.55:r9gqD6J7@1/Index:

term: binomial distribution
link text: 8.3 | A Population Proportion
link href: http://cte-cnx-dev.cnx.org/contents/30189442-6998-4686-ac05-ed152b91b9de@17.55:105#term160
