### ISSUE TITLE
publishing composite modules does not update moduleid sequence

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-publishing#140]
Each collation/cooking of a book creates new `CompositeModules`. These are inserted into the `modules` table, and consume legacy `moduleid`s. However the `moduleid_seq` seems to not get updated, so when legacy tries to get a new ID, it is given one that already exists, then fails on publishing new modules.

**Comment by reedstrm** [comment]
The code looks correct at first glance, (it's using the DEFAULT insert, doesn't seem to do any math to create a new moduleid. Perhaps we've got some sort of DB level sharing problem.

**Comment by reedstrm** [comment]
moved to archive (where the code is)

**Comment by reedstrm** [comment]
I think I've found it over in the cnx-archive legacy publishing code, which does a setval on the sequence, using only Modules (or Collections) Checking to see why it does that.

**Comment by pumazi** [comment]
IIRC we made the change to use setval on the sequence and have the rhaptos code bump the sequence when it creates an id.

**Comment by reedstrm** [comment]
resolved w/ cnx-archive#480
