### ISSUE TITLE
composite pages are being assigned uuids that are not in the document_controls table

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-publishing#183]
found during baking tests on qa, there were colliding uuids (derived copy of University Physics vs. "confidence interval" module in Statistics)

**Comment by reedstrm** [comment]
Turns out this had nothing to do with assigning colliding uuids, but w/ assigning colliding values moduleid, for collections (`colXXXXX`) Fixed in https://github.com/Rhaptos/Products.RhaptosModuleStorage/pull/19 and https://github.com/Rhaptos/Products.RhaptosRepository/pull/17
