### ISSUE TITLE
baking monitoring tool => change timestamps to local time

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-publishing#188]
Found on https://archive-staging.cnx.org/a/content-status/: The timezone of the timestamps in `Created` is sometime in the future, please make them Houston time.

![image](https://user-images.githubusercontent.com/11298165/30877142-69b3f78c-a2be-11e7-8524-5df9f1a16593.png)

cc @brittweinstein

**Comment by reedstrm** [comment]
```staging00.cnx.org Tue Sep 26 13:52:58 CDT 2017
staging01.cnx.org Mon Sep 25 10:47:34 UTC 2017
staging02.cnx.org Tue Sep 26 13:57:23 CDT 2017
staging03.cnx.org Tue Sep 26 13:58:44 CDT 2017
staging04.cnx.org Mon Sep 25 03:44:27 UTC 2017
staging05.cnx.org Mon Sep 25 06:52:08 UTC 2017
staging06.cnx.org Tue Sep 26 18:53:04 UTC 2017
staging07.cnx.org Mon Sep 25 09:13:56 UTC 2017
staging08.cnx.org Tue Sep 26 18:53:06 UTC 2017
staging09.cnx.org Tue Sep 26 18:53:06 UTC 2017
staging10.cnx.org Tue Sep 26 13:53:06 CDT 2017
```

**Comment by kerwinso** [comment]
I believe baking is happening on staging08.

**Comment by karenc** [comment]
We might want to add the timezone as a config (in development.ini) and use it in the code.  For example, the timezone for central time is `US/Central` (or `America/Chicago`).  If we get a datetime object `created`, we can do `created.astimezone(tz=pytz.timezone(config.TZ))` or something like that.

**Comment by reedstrm** [comment]
Right now, it's using whatever timezone the server is in, right? Ideally, it should report in the _viewers_ timezone, but that's crazy talk!

**Comment by reedstrm** [comment]
```$ for i in {00..10}; do h=staging$i; echo -n $h' '; ssh $h 'cat /etc/timezone'; done
staging00 America/Chicago
staging01 Etc/UTC
staging02 America/Chicago
staging03 America/Chicago
staging04 Etc/UTC
staging05 Etc/UTC
staging06 Etc/UTC
staging07 Etc/UTC
staging08 Etc/UTC
staging09 Etc/UTC
staging10 America/Chicago
```

**Comment by philschatz** [comment]
What if it used the browser's timezone? (I think JS has access to that)

**Comment by reedstrm** [comment]
Right, see my comment above. :-)

**Comment by kerwinso** [comment]
Related card: https://trello.com/c/lAYdPZi7

**Comment by kerwinso** [comment]
FYI: On qa, the timestamps appear to be correct somehow.

![image](https://user-images.githubusercontent.com/11298165/32079457-49ca2b3e-ba70-11e7-971f-0f981a09e615.png)

**Comment by openstaxalina** [comment]
I will create a card for this on the DevOps board.  Another option would be for the timestamps to match whatever timezone the viewer is in.

**Comment by openstaxalina** [comment]
I will close this issue once I have created the cards on the DevOps board.

**Comment by kerwinso** [comment]
Timezone updated on the staging server. However, we need to add a feature to the GOB content status tool  to display the local time on the frontend regardless of what time zone the server that hosts the tool is set to. 

Here's the new Trello card for that:
https://trello.com/c/HyocXQiJ/136-content-status-monitoring-tool-timestamps-should-display-in-houston-time

**Comment by openstaxalina** [comment]
This will be Javascript work.

**Comment by openstaxalina** [comment]
Also need to write Javascript tests for GOB.

**Comment by openstaxalina** [comment]
This has been resolved - closing.
