### ISSUE TITLE
baking monitoring tool => add HTML title/ browser metadata

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-publishing#189]
When I have a browser with multiple open tabs, it's often hard to find which tab had the Content Status Tool open since there's no title metadata, just the URL visible in the tab.

![image](https://user-images.githubusercontent.com/11298165/30884577-cb811dc0-a2d5-11e7-8ac4-188b9d0c1839.png)

@brittweinstein Please comment with what your request for what the title of the browser tab would be, e.g. "Baking Monitoring Tool - [servername]" or whatever.

**Comment by brittweinstein** [comment]
Let's settle with "GOB - [servername]"

**Comment by kerwinso** [comment]
Needs testing on qa after deployment. Related card: https://trello.com/c/UlxSjETd

**Comment by kerwinso** [comment]
Look at that beautiful GOB. (verified on qa)

![image](https://user-images.githubusercontent.com/11298165/32078884-303c773c-ba6e-11e7-8c8e-79ea9c645a64.png)
