### ISSUE TITLE
baking monitoring tool => display STARTED state from celery

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-publishing#191]
Currently on https://staging.cnx.org/a/content-status/, there are only 2 states that display when a bake is successful: `QUEUED` and `SUCCESS`. We don't know if a baking job has actually started.

Ross's `bake_logs.sh` script provides access to more detailed processing messages. ~~Can we add these messages to the content status tool?~~

Compare in the table below (Steps after publish):

| bake_logs                                       	| content status tool 	|
|-------------------------------------------------    	|---------------------	|
| --                                                                           | PENDING |            |
| Queued for processing                                   	| QUEUED              	|
| Starting baking                                               	| STARTED                  	|
| Exported                                                          	| --                  	|
| Finished baking with a final state of 'current' 	| SUCCESS             	|

## EDIT 10/20/17:
The request (based on [this discussion](https://github.com/Connexions/cnx-publishing/pull/197#issuecomment-338317607)) is now just to enable the `STARTED` state in celery and display that state in the content status (GOB) tool (with accompanying filter).

**Comment by kerwinso** [comment]
Related card: https://trello.com/c/lAYdPZi7

**Comment by reedstrm** [comment]
Note that PENDING might occur if were having issues with the database to queue connectivity

**Comment by kerwinso** [comment]
This worked on qa, but not on staging (https://staging.cnx.org/a/content-status/). It only shows `QUEUED`, not `STARTED`.

**Comment by kerwinso** [comment]
Works now on https://staging.cnx.org/a/content-status/, possibly related to that CSS issue, dunno. :man_shrugging: 

![image](https://user-images.githubusercontent.com/11298165/32463843-95dd75e4-c303-11e7-9311-f0788c339048.png)
