### ISSUE TITLE
baking monitoring tool=> filter for QUEUED jobs

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-publishing#193]
On https://staging.cnx.org/a/content-status/, we had a filter on for a uuid and it did _not_ show a `QUEUED` job that was active. (Is `PENDING` the same as `QUEUED`?) In any case, there should be a working filter that shows `QUEUED` jobs when filtering by author and/or uuid.

cc @brittweinstein 

EDIT: per [this comment](https://github.com/Connexions/cnx-publishing/pull/197#issuecomment-338317607), known tasks are `QUEUED`, unknown tasks are still `PENDING`.

**Comment by kerwinso** [comment]
Needs testing on qa after deployment. Related card: https://trello.com/c/lAYdPZi7

**Comment by reedstrm** [comment]
yeah, sorry got auto-closed by commit

**Comment by kerwinso** [comment]
[Whoomp! There It Is](https://youtu.be/uVkAbi2Bwf4) (on qa):

![image](https://user-images.githubusercontent.com/11298165/32079560-bfed8306-ba70-11e7-9a21-8808ae86afce.png)
