### ISSUE TITLE
GOB / Content Status Tool 404 under "None" recipe book Print Style links

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-publishing#206]
# Scenario

On the GOB / Content Status tool clicking on the “Print Style” link for a book that has a recipe value of “None” brings you to a 404 page stating “the resource could not be found, Invalid print style: <print style>

# Reproducibility Details

* **Impact area**: GOB Tool
*  **User**: Kerwin / Ross
*  **URL / Location**: https://qa.cnx.org/a/content-status/
* **How many times were you able to reproduce the issue?** Readily reproducable

*  **Steps to reproduce**:

1. Open the GOB tool (see URL above)
2. Click on the Print Style for a book with “None” as the value in the “Recipe” field.
3. You have arrived at your destination.

* **Images or screenshots Included:** Yes  (_attach below_)
![image](https://user-images.githubusercontent.com/12678235/32736064-2cb83bfe-c85c-11e7-950f-2223f65e7863.png)
![image](https://user-images.githubusercontent.com/12678235/32736164-62286444-c85c-11e7-9539-5af1eec03964.png)

# Environment:

* **Instance**: QA
* **OS**: macOS
* **Browser**: Chrome

**Comment by kerwinso** [comment]
Needs verification on qa after deployment.

**Comment by kerwinso** [comment]
Technically these links work on qa now, they no longer 404, so this bug can be closed.

However in the process of fixing this, a couple other bugs were found. They were put into Trello here and will need to be prioritized:

https://trello.com/c/f8RJJHHQ/138-gob-content-status-tool-some-links-to-books-return-400-error
https://trello.com/c/fWxHq1hm/139-gob-content-status-tool-some-print-styles-say-0-books
