### ISSUE TITLE
Add "Fallback" state to GOB

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-publishing#224]
# Description
Add a state called "Fallback" to cnx.org/a/content-status. The behavior that puts a content in this state is not through a publication, but instead via recipe upgrade. When cnx-recipes is updated and released, a database migration step in cnx-db is executed to "bake" books that have an updated recipe.

When the migration invokes a "bake" with the newest recipe has failed, the content _falls back_ to the previous version of the recipe. The previous bake was successful, so no modifications to the content should be required; thus leaving the previous baked content in-place. When this has occurred, we'd like the UI to display "Fallback" as the state.

---

Older preserved notes:

> This state will be displayed under the following conditions:
> - book fails to bake with current recipe, then:
> - book successfully bakes with the most recent recipe the previous version of the book successfully baked with

# Acceptance Criteria:

- The state "Fallback" displays when the above condition are met.
- A yellow checkmark displays next to the word "Fallback" under the "State" column.
- A user is able to filter by the state "Fallback"  

# Test Plan
 - Select a book that has been baked successfully on the server under test (preferably via print-style-w-recipe) 
- record the uuid@version, and the hash of the recipe used to bake.
 - inject a known bad recipe, via cnx-archive-inject_resource cli script:
       example:
           ` /var/cnx/venvs/archive/bin/cnx-archive-inject_resource --media-type text/css --resource-filename ruleset.css /etc/cnx/archive/app.ini e48dfd6f-2533-402c-8587-6ff18b6c157c@1.24 /home/reedstrm/bad.css`

Where `bad.css` contains a single line `this :` which is not valid CSS (but not empty)

- book will show up in GOB as "queued" then "processing", then "fallback" pointing to known good recipe.
 - book will be baked on webview.

# PRs:
https://github.com/Connexions/cnx-publishing/pull/230

**Comment by kerwinso** [comment]
I don't know how to manually make a book fail baking --  @reedstrm are you able to add that info to this issue?

**Comment by pumazi** [comment]
🤔 If only there was a way to throw an error in a recipe... Connexions/cnx-easybake#93 😉

**Comment by pumazi** [comment]
I've updated the description to elaborate on when this state is happens and how it comes to happen.

**Comment by brittweinstein** [comment]
@reedstrm will create and share test plan

**Comment by kerwinso** [comment]
log in to staging07 or staging08 to test

**Comment by kerwinso** [comment]
## My test steps
1. Successfully bake col11562 (Introductory Statistics) via Statistics print parameter with recipe. It became uuid@version `30189442-6998-4686-ac05-ed152b91b9de@22.1` with a recipe hash of `7d8520af6178d175b9943c0e82bd1ffeeea0098f` (`statistics 1.6.0`).
1. Log on to staging08.cnx.org.
1. Run this command: `/var/cnx/venvs/archive/bin/cnx-archive-inject_resource --media-type text/css --resource-filename ruleset.css /etc/cnx/archive/app.ini 30189442-6998-4686-ac05-ed152b91b9de@22.1 /home/reedstrm/bad.css`
1. Get this result:

```
/var/cnx/venvs/archive/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be 
renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: 
<http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Using:
  filename: ruleset.css
  media_type: text/css
/resources/52b0adf2f1965dccd503728db8bf3487ed91b8e9
kerwin@staging08:~$ 

```

## Results from GOB
In [GOB](https://staging.cnx.org/a/content-status/), the book [Introductory Statistics](https://staging.cnx.org/a/content-status/30189442-6998-4686-ac05-ed152b91b9de) was shown as being `QUEUED` immediately after resource injection -- but with the previously good recipe (`7d8520af6178d175b9943c0e82bd1ffeeea0098f`), NOT the new bad recipe (`52b0adf2f1965dccd503728db8bf3487ed91b8e9`). 

After about 10 minutes, the book successfully bakes with the previous recipe. There is no mention of fallback in GOB.

So after following the test plan, I'm seeing 2 bugs:
1. After manual injection, GOB should have linked to the new bad recipe, not the previous successful recipe. (Granted, this is not part of the Acceptance Criteria above, but it probably should be -- cc @openstaxalina) 
2. After manual injection of a bad recipe, the Fallback flow and state should have been invoked for that baking job -- but GOB shows no record of it.

This suggests to the user that the system is re-using the last known good recipe without even trying the new (manually injected) one. So either the test plan needs revising, or something isn't working as designed in the code, or possibly both. 

@reedstrm @TomWoodward Please advise.

**Comment by kerwinso** [comment]
OK, worked with Ross on this: 
# New test plan: 
Manually inject a good ruleset to an unbaked collection, then manually inject a bad ruleset to the same collection. I did this with Biology (col11448) on staging.

## First, manually inject good recipe

```
kerwin@staging08:~$ /var/cnx/venvs/archive/bin/cnx-archive-inject_resource --media-type text/css --resource-filename ruleset.css /etc/cnx/archive/app.ini 185cbf87-c72e-48f5-b51e-f14f21b5eabd@13.1 biology/biology.css
/var/cnx/venvs/archive/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Using:
  filename: ruleset.css
  media_type: text/css
/resources/aa9561c6bd264390c8e1df65e9e301430464a06c
kerwin@staging08:~$ 
```

## Did it bake successfully?
Yes, also GOB is showing the correct hash of the ruleset. 

## Then, manually inject bad recipe
```
$ /var/cnx/venvs/archive/bin/cnx-archive-inject_resource --media-type text/css --resource-filename ruleset.css /etc/cnx/archive/app.ini 185cbf87-c72e-48f5-b51e-f14f21b5eabd@13.1 /home/reedstrm/bad.css
/var/cnx/venvs/archive/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Using:
  filename: ruleset.css
  media_type: text/css
/resources/52b0adf2f1965dccd503728db8bf3487ed91b8e9
```

## Did it fall back?
Yes! Although it marked both recent (manual test injection) jobs as fallback (and not just the most recent one), it is functioning according to Acceptance Criteria and hence considered Passed. 

![image](https://user-images.githubusercontent.com/11298165/44425826-9e81ad00-a552-11e8-8848-3d996ec7baf4.png)

## Additional Notes

The multiple fallback indicators (which are not  accurate historically) have something to do with the fact that there's only one custom recipe slot for that collection version number, which is more visible due to the artificial way we tested this (i.e., via manual ruleset injection). Note that fallback also reverts all the custom recipe IDs for Biology back to the last successfully baked recipe (`aa9561c6bd264390c8e1df65e9e301430464a06c`): https://staging.cnx.org/a/content-status/185cbf87-c72e-48f5-b51e-f14f21b5eabd 

@reedstrm can explain this better than I, but my understanding is that it's not really fixable. However, I don't expect the multiple-fallback scenario to occur in real life (and a fallback situation has never actually occurred in the wild), so I am not too worried about it.
