### ISSUE TITLE
Page published successfully, but gives 404

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-publishing#71]
Dante published a Page, but it does not display.

http://demo.cnx.org/contents/f07d37b0-f5e5-40bf-b824-eb91f81d6ea2@1/Test

**Comment by edwoodward** [comment]
Chat between Michael and Ross regarding the issue

(01/22/2015 01:20:43 PM) reedstrm: There's one from 2015-01-21 12:32:58,593 ERROR [waitress][Dummy-1] Exception when serving /publications

(01/22/2015 01:21:11 PM) reedstrm: so not todays problem. 
(01/22/2015 01:23:38 PM) reedstrm: Hmm, I see an invalid reference for an image, pointing at http://demo.cnx.org/images/logo.png  Why is that invalid?
(01/22/2015 01:24:51 PM) pumazi: It probably saw cnx.org and processed it as an internal resource.
(01/22/2015 01:25:02 PM) reedstrm: ah ha.
(01:30:30 PM) reedstrm: I see the check, but don't understand it's purpose. It labels any link w/ cnx.org in it as invalid, AFAICT.
(01:32:19 PM) pumazi: All internal refs were to be relative.
(01:32:58 PM) pumazi: IIRC, this was for offline epub purposes.
(01:37:18 PM) pumazi: Hrm… maybe our ``data:`` related changes went a bit too far. Still tracking backwards…
(01:37:23 PM) reedstrm: But this was not classified as INTERNAL_REFERNCE_TYPE
(01:37:24 PM) reedstrm: o.k.
(01:39:30 PM) pumazi: nope, not ``data:`` related.
(01:41:19 PM) pumazi: Seems to be a disconnect between what publishing and epub see as internal.
(01:41:33 PM) reedstrm: ah
(01:41:45 PM) pumazi: So publishing is assuming that anything cnx.org is probably internal and therefore it's a user error.
(01:41:51 PM) reedstrm: your left and right hands :-)
(01:41:57 PM) pumazi: But as you pointed out that may not be the case.
(01:43:18 PM) pumazi: The idea was to prevent people from putting in absolute links. This was incase we at some point want/need to change the url scheme again.
(01:43:53 PM) reedstrm: absolute links to internal stuff.
(01:44:06 PM) pumazi: Yes
(01:45:41 PM) dennis has set the subject to: cnx rewrite, all topics
(01:45:41 PM) pumazi: It's a form of data integrity that was done in support of the offline epub idea.
(01:46:45 PM) pumazi: The html in the offline epub would then be almost exactly what we would view on an archive route for /contents/{ident-hash}.html
(01:49:01 PM) pumazi: Aha, now I remember! I didn't put the same logic in cnx-epub, because I wanted it to be as unbiased about who is using it (i.e. cnx, syvula, vietnam, etc.)
(01:50:01 PM) pumazi: … as possible. Because it is the most reusable library of all the packages we have created. And it could be used by a third-party to produce publications.
(02:07:49 PM) reedstrm: So it need ssome sort of config to tell it 'consider these URLs local' Or we just nedd to take the test out of publishing.
(02:09:36 PM) reedstrm: In any case, I probably shouldn't have pulled you off xslt. I'll throw a note on the issue w/ your comments.
(02:09:44 PM) pumazi: Probably just need to take the condition out of publishing. But that will sacrifice some data integrity.

**Comment by rich-hart** [comment]
This issue can probably be fixed by modifying the [mark_invalid_reference](https://github.com/Connexions/cnx-publishing/blob/83f1e9c355deadfd28178e30adfc33b2ab112fd7/cnxpublishing/db.py#L531-L562) function in publishing/db.py . It'd be great if we could correct the invalid references from external --> internal i.e. given [this line in test_db.py](https://github.com/Connexions/cnx-publishing/blob/83f1e9c355deadfd28178e30adfc33b2ab112fd7/cnxpublishing/tests/test_db.py#L983-L985) can we modify the mark_invalid_reference function to change the external link to the correct internal reference?  The same would go for the link to the image resource http://demo.cnx.org/images/logo.png.

**Comment by pumazi** [comment]
Just [remove the last condition](https://github.com/Connexions/cnx-publishing/blob/83f1e9c355deadfd28178e30adfc33b2ab112fd7/cnxpublishing/db.py#L560). Anything that points at 'cnx.org' is fine (or at least that was the conclusion from the conversation Ross and I had). It would be nice to ensure the reference is good. But it doesn't seem overly important at this time.

**Comment by rich-hart** [comment]
Works for me!
