### ISSUE TITLE
Incorrect legacy moduleid for collections

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-publishing#73]
Publishing is creating records with portal_type 'Collection' but moduleids starting w/ 'm'

**Comment by pumazi** [comment]
This is likely an issue with the assign_moduleid_default_trigger in cnx-archive.

**Comment by pumazi** [comment]
@reedstrm tracked this down to a deployment issue, where the assign_moduleid_default_trigger was currently not functional.
