### ISSUE TITLE
Roles not changing

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-publishing#98]
I added a user as copyright holder and publisher which worked and I could publish.  I then switched them to an author and removed the other 2.  The role acceptance displays the 2 previous roles and not the new one. This worked before.

http://dev.cnx.org/contents/a375c585-ffa7-4da9-9fcc-167baa331e49@draft/Roles_Test

**Comment by pumazi** [comment]
@edwoodward I followed your instructions. And I **could not reproduce** this. However, I have determined that the piece of content you reference does still have 'ew3' as a publisher and copyright-holder.
